name = "martin-audio-labs-publisher"
main = "worker.js"
compatibility_date = "2026-10-08"
workers_dev = true

[vars]
GITHUB_CLIENT_ID = "Iv23lielIooQlMkrIA3k"
GITHUB_OWNER = "martinaudiolab"
GITHUB_REPOSITORY = "martinaudiolab"
GITHUB_BRANCH = "main"
ALLOW_NON_ADMIN_PUBLISHING = "false"
SITE_ORIGIN = "https://martinaudiolab-main.thealexandersound.workers.dev"

[[kv_namespaces]]
binding = "PUBLISHER_SESSIONS"
id = "f4f108b8ca2c4aca9bed64487b7bbce5"

[env.testing]
name = "martin-audio-labs-publisher-test"
workers_dev = true

[env.testing.vars]
GITHUB_CLIENT_ID = "REPLACE_WITH_TEST_GITHUB_APP_CLIENT_ID"
GITHUB_OWNER = "martinaudiolab"
GITHUB_REPOSITORY = "martinaudiolab"
GITHUB_BRANCH = "post-builder-test"
ALLOW_NON_ADMIN_PUBLISHING = "true"
SITE_ORIGIN = "https://martinaudiolab-main.thealexandersound.workers.dev"

[[env.testing.kv_namespaces]]
binding = "PUBLISHER_SESSIONS"
id = "37c0bf2d56b14f4ba4d7fe0ddfa64817"