#!/usr/bin/env node
// Builds the Shop pages (site/shop/*.html) from shop-data/items.json.
// Usage, from the repository root:  node scripts/build-shop.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE = path.join(ROOT, "site");
const OUT = path.join(SITE, "shop");
const MARK = "<!-- generated by scripts/build-shop.mjs: do not edit by hand -->";
const BRAND = "Martin Audio Labs";
const STATUS = { available: "", pending: "Sale pending", sold: "Sold" };
const errors = [];
const warnings = [];

const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const money = (n) => "$" + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

let data;
try {
  data = JSON.parse(fs.readFileSync(path.join(ROOT, "shop-data", "items.json"), "utf8"));
} catch (e) {
  console.error("Could not read shop-data/items.json: " + e.message);
  process.exit(1);
}
const shop = data.shop || {};
const placeholder = shop.placeholder || "images/banner.jpg";
const email = shop.email || "";
const items = Array.isArray(data.items) ? data.items : [];

const slugs = new Set();
items.forEach((it, i) => {
  const where = "Item " + (i + 1) + (it.title ? " (" + it.title + ")" : "");
  if (!it.title) errors.push(where + ": missing title");
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(it.slug || "")) errors.push(where + ': slug must be lowercase letters, numbers and hyphens, e.g. "marantz-2270"');
  else if (it.slug === "index") errors.push(where + ': slug cannot be "index"');
  else if (slugs.has(it.slug)) errors.push(where + ": duplicate slug " + it.slug);
  slugs.add(it.slug);
  const st = it.status || "available";
  if (!(st in STATUS)) errors.push(where + ': status must be "available", "pending" or "sold"');
  if (it.price != null && typeof it.price !== "number" && typeof it.price !== "string") errors.push(where + ": price must be a number or text");
  it.images = Array.isArray(it.images) && it.images.length ? it.images : [placeholder];
  it.images.forEach((p) => {
    if (!/^https?:/.test(p) && !fs.existsSync(path.join(SITE, p.replace(/^\//, "")))) warnings.push(where + ": image not found: " + p);
  });
});
if (errors.length) {
  console.error("Shop not built. Fix these problems in shop-data/items.json:\n - " + errors.join("\n - "));
  process.exit(1);
}

const imgSrc = (p) => (/^(https?:|\/)/.test(p) ? p : "../" + p);
const status = (it) => it.status || "available";
const priceHtml = (it) => {
  if (status(it) === "sold") return "Sold";
  if (typeof it.price === "number") {
    return typeof it.was === "number" ? "<s>" + money(it.was) + "</s> " + money(it.price) : money(it.price);
  }
  return it.price ? esc(it.price) : "Inquire for price";
};
const paras = (d) => (Array.isArray(d) ? d : d ? [d] : []).map((p) => "<p>" + esc(p).replace(/\n/g, "<br>") + "</p>").join("");

const links = [
  ["../index.html", "Home", ""], ["../stereo/index.html", "Stereo Repair", "stereo"], ["../radio/index.html", "Radio Repair", "radio"],
  ["../test-equipment/index.html", "Test Equipment", "test-equipment"], ["../shop/index.html", "Shop", "shop"], ["../contact.html", "Contact", ""]
];
const nav = () => links.map((l) => '<a href="' + l[0] + '"' + (l[2] === "shop" ? ' class="on" aria-current="page"' : "") + ">" + l[1] + "</a>").join("");
const THEME = '<script>(function(){var r=document.documentElement;try{var t=localStorage.getItem("th");if(t)r.setAttribute("data-theme",t)}catch(e){}document.getElementById("th").onclick=function(){var d=r.getAttribute("data-theme")==="dark"||(!r.getAttribute("data-theme")&&matchMedia("(prefers-color-scheme:dark)").matches),n=d?"light":"dark";r.setAttribute("data-theme",n);try{localStorage.setItem("th",n)}catch(e){}}})()</script>';
const page = (title, desc, inner) => '<!DOCTYPE html>\n' + MARK + '\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>' + esc(title) + '</title><meta name="description" content="' + esc(desc) + '"><link rel="stylesheet" href="../style.css"></head><body><header class="site"><a class="brand" href="../index.html">' + BRAND + '</a><nav>' + nav() + '<button class="theme" type="button" id="th">Theme</button></nav></header><main>' + inner + '</main>' + THEME + '</body></html>\n';

const ordered = items.filter((i) => status(i) !== "sold").concat(items.filter((i) => status(i) === "sold"));

const card = (it) => {
  const badge = STATUS[status(it)] ? '<span class="shop-badge">' + STATUS[status(it)] + "</span>" : "";
  return '<li class="shop-card' + (status(it) === "sold" ? " sold" : "") + '"><a href="' + it.slug + '.html"><div class="shop-thumb"><img src="' + esc(imgSrc(it.images[0])) + '" alt="" loading="lazy">' + badge + "</div><strong>" + esc(it.title) + "</strong>" + (it.summary ? '<span class="shop-sum">' + esc(it.summary) + "</span>" : "") + '<span class="shop-price">' + priceHtml(it) + "</span></a></li>";
};

const indexInner = '<h1 class="h2" style="font-size:2rem">' + esc(shop.title || "Shop") + "</h1>" +
  (shop.intro ? '<p class="intro">' + esc(shop.intro) + "</p>" : "") +
  (shop.howToBuy ? '<p class="shop-note">' + esc(shop.howToBuy) + "</p>" : "") +
  (ordered.length ? '<ul class="shop-grid">' + ordered.map(card).join("") + "</ul>" : "<p>Nothing is listed right now. Please check back soon.</p>");

const detail = (it) => {
  const st = status(it);
  const subject = encodeURIComponent("Inquiry: " + it.title);
  const body = encodeURIComponent("Hello,\n\nI would like to ask about: " + it.title + "\n\nThank you,\n");
  const specs = Array.isArray(it.details) && it.details.length ? '<dl class="shop-specs">' + it.details.map((d) => "<dt>" + esc(d[0]) + "</dt><dd>" + esc(d[1]) + "</dd>").join("") + "</dl>" : "";
  const more = it.images.length > 1 ? '<div class="shop-more">' + it.images.slice(1).map((p) => '<img src="' + esc(imgSrc(p)) + '" alt="' + esc(it.title) + ' (additional photo)" loading="lazy">').join("") + "</div>" : "";
  const action = st === "sold" ? '<p class="shop-note">This item has been sold.</p>' : email ? '<p><a class="btn" href="mailto:' + esc(email) + "?subject=" + subject + "&amp;body=" + body + '">Inquire about this item</a></p>' : "";
  return '<a class="back" href="index.html">Back to ' + esc(shop.title || "Shop") + '</a><article class="shop-detail"><div class="shop-gallery"><img class="shop-main" src="' + esc(imgSrc(it.images[0])) + '" alt="' + esc(it.title) + '">' + more + '</div><div class="shop-info"><h1>' + esc(it.title) + "</h1>" +
    (it.category ? '<div class="meta">' + esc(it.category) + (STATUS[st] ? " &nbsp;|&nbsp; " + STATUS[st] : "") + "</div>" : "") +
    '<div class="shop-price big">' + priceHtml(it) + "</div>" +
    (it.sample ? '<p class="shop-note">Sample listing. Replace or remove it before the shop goes live.</p>' : "") +
    '<div class="body">' + paras(it.description) + "</div>" + specs + action + "</div></article>";
};

fs.mkdirSync(OUT, { recursive: true });
for (const f of fs.readdirSync(OUT)) {
  const p = path.join(OUT, f);
  if (f.endsWith(".html") && fs.readFileSync(p, "utf8").includes(MARK)) fs.unlinkSync(p);
}
fs.writeFileSync(path.join(OUT, "index.html"), page((shop.title || "Shop") + " - " + BRAND, shop.intro || "Shop", indexInner));
for (const it of items) fs.writeFileSync(path.join(OUT, it.slug + ".html"), page(it.title + " - " + (shop.title || "Shop") + " - " + BRAND, it.summary || it.title, detail(it)));

const samples = items.filter((i) => i.sample).length;
console.log("Built shop: " + items.length + " item" + (items.length === 1 ? "" : "s") + " + gallery page in site/shop/");
if (samples) console.log("NOTE: " + samples + " item(s) are marked sample. Remove them from shop-data/items.json before going live.");
warnings.forEach((w) => console.log("Warning: " + w));
