// Pure shop rendering shared by scripts/build-shop.mjs (local CLI) and
// publisher/worker.js (the shop builder). No file-system or runtime APIs here.

import { NAV_SCRIPT, navHtml } from "./site-nav.mjs";
import { normalizeContent } from "./site-content.mjs";
import { heroHtml, themeAttr } from "./site-render.mjs";

export const SHOP_MARK ="<!-- generated by scripts/build-shop.mjs: do not edit by hand -->";
const STATUS = { available: "", pending: "Sale pending", sold: "Sold" };
export const STATUS_KEYS = Object.keys(STATUS);
const SLUG = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const LOCAL_IMAGE = /^images\/[a-zA-Z0-9][a-zA-Z0-9._\/-]*\.(jpe?g|png|webp|gif)$/;

const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const money = (n) => "$" + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

/**
 * Checks shop data. Returns { errors, warnings }. Normalises item.images in place
 * (empty list becomes the placeholder). `imageExists(path)` is optional and only
 * used to produce warnings for missing local images.
 */
export function validateShop(data, imageExists) {
  const errors = [];
  const warnings = [];
  const shop = (data && data.shop) || {};
  const placeholder = shop.placeholder || "images/banner.jpg";
  const items = data && Array.isArray(data.items) ? data.items : [];
  const slugs = new Set();
  items.forEach((it, i) => {
    const where = "Item " + (i + 1) + (it.title ? " (" + it.title + ")" : "");
    if (!it.title) errors.push(where + ": missing title");
    if (!SLUG.test(it.slug || "")) errors.push(where + ': slug must be lowercase letters, numbers and hyphens, e.g. "marantz-2270"');
    else if (it.slug === "index") errors.push(where + ': slug cannot be "index"');
    else if (slugs.has(it.slug)) errors.push(where + ": duplicate slug " + it.slug);
    slugs.add(it.slug);
    const st = it.status || "available";
    if (!(st in STATUS)) errors.push(where + ': status must be "available", "pending" or "sold"');
    if (it.price != null && typeof it.price !== "number" && typeof it.price !== "string") errors.push(where + ": price must be a number or text");
    if (typeof it.price === "number" && !(Number.isFinite(it.price) && it.price >= 0)) errors.push(where + ": price must be zero or more");
    if (it.was != null && !(typeof it.was === "number" && Number.isFinite(it.was) && it.was >= 0)) errors.push(where + ': "was" price must be a number');
    it.images = Array.isArray(it.images) && it.images.length ? it.images : [placeholder];
    it.images.forEach((p) => {
      if (typeof p !== "string" || !(/^https?:\/\//.test(p) || LOCAL_IMAGE.test(p.replace(/^\//, "")))) errors.push(where + ": unsupported image path " + p);
      else if (imageExists && !/^https?:/.test(p) && !imageExists(p.replace(/^\//, ""))) warnings.push(where + ": image not found: " + p);
    });
  });
  return { errors, warnings };
}

const imgSrc = (p) => (/^(https?:|\/)/.test(p) ? p : "../" + p);
const status = (it) => it.status || "available";
const priceHtml = (it) => {
  if (status(it) === "sold") return "Sold";
  if (typeof it.price === "number") {
    return typeof it.was === "number" ? "<s>" + money(it.was) + "</s> " + money(it.price) : money(it.price);
  }
  return it.price ? esc(it.price) : "Inquire for price";
};
const paras = (d) => (Array.isArray(d) ? d : d ? [d] : []).map((p) => "<p>" + esc(p).replace(/\n/g, "<br>") + "</p>").join("");

const THEME = '<script>(function(){var r=document.documentElement;try{var t=localStorage.getItem("th");if(t)r.setAttribute("data-theme",t)}catch(e){}document.getElementById("th").onclick=function(){var d=r.getAttribute("data-theme")==="dark"||(!r.getAttribute("data-theme")&&matchMedia("(prefers-color-scheme:dark)").matches),n=d?"light":"dark";r.setAttribute("data-theme",n);try{localStorage.setItem("th",n)}catch(e){}}})()</script>';
const LIGHTBOX = '<script src="../lightbox.js" defer></script>';
const page = (ctx, title, desc, inner, extra, o = {}) =>'<!DOCTYPE html>\n' + SHOP_MARK + '\n<html lang="en"' + themeAttr(ctx.content) + '><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><title>' + esc(title) + '</title><meta name="description" content="' + esc(desc) + '"><link rel="stylesheet" href="../style.css"></head><body' + (o.bodyClass ? ' class="' + o.bodyClass + '"' : "") + '><header class="site"><a class="brand" href="../index.html">' + esc(ctx.content.site_name) + '</a>' + navHtml(ctx.content.nav_items, "shop/index.html", "../") + '</header>' + (o.beforeMain || "") + '<main>' + inner + '</main>' + (extra || "") + NAV_SCRIPT("../") + THEME + '</body></html>\n';

/**
 * Renders the gallery and one page per item.
 * Returns an object mapping file name (relative to site/shop/) to HTML.
 * Call validateShop first; it fills in each item's images.
 */
export function renderShop(data, options) {
  const ctx = { content: normalizeContent(options && options.content) };
  const shop = data.shop || {};
  const email = shop.email || "";
  const items = Array.isArray(data.items) ? data.items : [];
  const ordered = items.filter((i) => status(i) !== "sold").concat(items.filter((i) => status(i) === "sold"));

  const card = (it) => {
    const badge = STATUS[status(it)] ? '<span class="shop-badge">' + STATUS[status(it)] + "</span>" : "";
    return '<li class="shop-card' + (status(it) === "sold" ? " sold" : "") + '"><a href="' + it.slug + '.html"><div class="shop-thumb"><img src="' + esc(imgSrc(it.images[0])) + '" alt="" loading="lazy">' + badge + "</div><strong>" + esc(it.title) + "</strong>" + (it.summary ? '<span class="shop-sum">' + esc(it.summary) + "</span>" : "") + '<span class="shop-price">' + priceHtml(it) + "</span></a></li>";
  };

  const indexInner =     (shop.howToBuy ? '<p class="shop-note">' + esc(shop.howToBuy) + "</p>" : "") +
    (ordered.length ? '<ul class="shop-grid">' + ordered.map(card).join("") + "</ul>" : "<p>Nothing is listed right now. Please check back soon.</p>");

  const detail = (it) => {
    const st = status(it);
    const subject = encodeURIComponent("Inquiry: " + it.title);
    const body = encodeURIComponent("Hello,\n\nI would like to ask about: " + it.title + "\n\nThank you,\n");
    const specs = Array.isArray(it.details) && it.details.length ? '<dl class="shop-specs">' + it.details.map((d) => "<dt>" + esc(d[0]) + "</dt><dd>" + esc(d[1]) + "</dd>").join("") + "</dl>" : "";
    const photos = it.images.map((p, n) => '<img class="shop-photo" src="' + esc(imgSrc(p)) + '" alt="' + esc(it.title) + (n ? " (photo " + (n + 1) + ")" : "") + '"' + (n ? ' loading="lazy"' : "") + ">").join("");
    const action = st === "sold" ? '<p class="shop-note">This item has been sold.</p>' : email ? '<p><a class="btn" href="mailto:' + esc(email) + "?subject=" + subject + "&amp;body=" + body + '">Inquire about this item</a></p>' : "";
    return '<a class="back" href="index.html">Back to ' + esc(shop.title || "Shop") + '</a><article class="shop-detail"><div class="shop-gallery">' + photos + '</div><div class="shop-info"><h1>' + esc(it.title) + "</h1>" +
      (it.category ? '<div class="meta">' + esc(it.category) + (STATUS[st] ? " &nbsp;|&nbsp; " + STATUS[st] : "") + "</div>" : "") +
      '<div class="shop-price big">' + priceHtml(it) + "</div>" +
      (it.sample ? '<p class="shop-note">Sample listing. Replace or remove it before the shop goes live.</p>' : "") +
      '<div class="body">' + paras(it.description) + "</div>" + specs + action + "</div></article>";
  };

  const files = {};
  // The shop page shares the homepage look: full-width slideshow (its own pool of photos) with the navigation floating over it.
  const hero = heroHtml({
    slides: ctx.content.shop_hero.slides, prefix: "../", title: shop.title || "Shop", subtitle: shop.intro || "", label: shop.title || "Shop"
  });
  files["index.html"] = page(ctx, (shop.title || "Shop") + " - " + ctx.content.site_name, shop.intro || "Shop", indexInner,
    '<script src="../hero.js" defer></script>', { bodyClass: "home", beforeMain: hero });
  for (const it of items) files[it.slug + ".html"] = page(ctx, it.title + " - " + (shop.title || "Shop") + " - " + ctx.content.site_name, it.summary || it.title, detail(it), LIGHTBOX);
  // Small public feed used by the homepage "For Sale Now" carousel.
  const feed = ordered.filter((it) => status(it) !== "sold").map((it) => ({
    slug: it.slug,
    title: it.title,
    image: it.images[0].replace(/^\//, ""),
    price: typeof it.price === "number" ? money(it.price) : it.price ? String(it.price) : "Inquire for price",
    was: typeof it.price === "number" && typeof it.was === "number" ? money(it.was) : "",
    pending: status(it) === "pending"
  }));
  files["feed.json"] = JSON.stringify(feed, null, 2) + "\n";
  return files;
}

const text =(v, max) => (typeof v === "string" ? v.trim().slice(0, max) : "");

/**
 * Reduces untrusted shop data to the known fields and sizes. Anything unknown
 * is dropped. Run validateShop on the result for the rules a person can fix.
 */
export function normalizeShop(input) {
  const src = input && typeof input === "object" ? input : {};
  const s = src.shop && typeof src.shop === "object" ? src.shop : {};
  const shop = {
    title: text(s.title, 80) || "Shop",
    intro: text(s.intro, 600),
    howToBuy: text(s.howToBuy, 600),
    email: text(s.email, 120),
    placeholder: /^images\/[a-zA-Z0-9._\/-]+$/.test(s.placeholder || "") ? s.placeholder : "images/banner.jpg"
  };
  const items = (Array.isArray(src.items) ? src.items : []).slice(0, 300).map((it) => {
    it = it && typeof it === "object" ? it : {};
    const out = { slug: text(it.slug, 80), title: text(it.title, 120), summary: text(it.summary, 200), category: text(it.category, 40) };
    if (typeof it.price === "number") out.price = it.price;
    else if (typeof it.price === "string" && it.price.trim()) out.price = it.price.trim().slice(0, 60);
    if (typeof it.was === "number") out.was = it.was;
    out.status = text(it.status, 20) || "available";
    out.images = (Array.isArray(it.images) ? it.images : []).filter((p) => typeof p === "string").slice(0, 16).map((p) => p.trim().slice(0, 200));
    const details = (Array.isArray(it.details) ? it.details : [])
      .filter((d) => Array.isArray(d) && typeof d[0] === "string" && typeof d[1] === "string" && d[0].trim())
      .slice(0, 24).map((d) => [d[0].trim().slice(0, 60), d[1].trim().slice(0, 200)]);
    if (details.length) out.details = details;
    out.description = (Array.isArray(it.description) ? it.description : []).filter((p) => typeof p === "string" && p.trim())
      .slice(0, 40).map((p) => p.trim().slice(0, 4000));
    if (it.sample === true) out.sample = true;
    return out;
  });
  return { shop, items };
}
