#!/usr/bin/env node
// Rewrites the top navigation in every hand-written or published page under site/
// so they all match scripts/site-nav.mjs. Safe to re-run.
// Usage, from the repository root:  node scripts/update-nav.mjs
// Pages generated by scripts/build-shop.mjs (site/shop/) are skipped: they are
// rebuilt from the same navigation module.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { NAV_SCRIPT, navHtml } from "./site-nav.mjs";
import { SHOP_MARK } from "./shop-render.mjs";

const SITE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "site");
const SECTION = { stereo: "stereo", radio: "radio", "test-equipment": "test-equipment" };

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full) : entry.name.endsWith(".html") ? [full] : [];
  });
}

function activeKey(rel) {
  const parts = rel.split("/");
  if (parts.length > 1) return SECTION[parts[0]] || (parts[0] === "shop" ? "shop" : "");
  return { "index.html": "home", "request.html": "request", "about.html": "about" }[rel] || "";
}

let changed = 0;
for (const file of walk(SITE)) {
  const rel = path.relative(SITE, file).split(path.sep).join("/");
  const raw = fs.readFileSync(file, "utf8");
  if (raw.includes(SHOP_MARK)) continue;
  const crlf = raw.includes("\r\n");
  let html = crlf ? raw.split("\r\n").join("\n") : raw;
  const prefix = rel.includes("/") ? "../" : "";
  const nav = html.match(/<nav>[\s\S]*?<\/nav>/);
  if (!nav) continue;
  html = html.replace(nav[0], () => navHtml(activeKey(rel), prefix));
  const script = NAV_SCRIPT(prefix);
  if (!html.includes(script)) html = html.replace("</body>", () => script + "</body>");
  if (crlf) html = html.split("\n").join("\r\n");
  if (html !== raw) { fs.writeFileSync(file, html); changed++; }
}
console.log("Updated navigation in " + changed + " page" + (changed === 1 ? "" : "s") + ".");
